spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://google.com.tw
          predicates:
            - Query=url,google

        - id: yahoo_route
          uri: https://yahoo.com.tw
          predicates:
            - Query=ya

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>.*), /renren-fast/$\{segment}